use_default_settings: true

server:
  # 本番運用では必ず変更すること
  secret_key: "changeme-please-set-a-random-string"
  limiter: false

outgoing:
  request_timeout: 20.0

search:
  formats:
    - html
    - json
